# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  ".data", # <epidist_diagnostics>
  "samples", # <epidist_diagnostics>
  ".data", # <as_latent_model.epidist_linelist>
  "woverlap", # <epidist_stancode.epidist_latent_model>
  ".data", # <as_naive_model.data.frame>
  ".data", # <observe_process>
  ".data", # <add_mean_sd.lognormal_samples>
  ".data", # <add_mean_sd.gamma_samples>
  "rlnorm", # <simulate_secondary>
  ".data", # <simulate_secondary>
  ".data", # <.replace_prior>
  "prior_new", # <.replace_prior>
  "source_new", # <.replace_prior>
  NULL
))
