# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  ".data", # <epidist_diagnostics>
  "samples", # <epidist_diagnostics>
  ".data", # <as_epidist_latent_model.epidist_linelist_data>
  "woverlap", # <epidist_stancode.epidist_latent_model>
  ".data", # <as_epidist_linelist_data.epidist_aggregate_data>
  ".data", # <.prepare_marginal_data>
  ".data", # <as_epidist_naive_model.epidist_linelist_data>
  ".data", # <plot_events>
  ".data", # <.plot_parameter_draws>
  ".data", # <.plot_delay_draws>
  ".data", # <plot_delays>
  ".data", # <.bin_delays>
  ".data", # <.delay_reference_layer>
  "rlnorm", # <simulate_secondary>
  ".data", # <simulate_secondary>
  ".data", # <simulate_dates>
  ".data", # <.replace_prior>
  NULL
))
